- .gitignore
- lib/mix/tasks/gen.referrals.ex
- lib/safira/contest/badge.ex
- lib/safira/contest/contest.ex
- lib/safira/contest/referral.ex
- lib/safira_web/controllers/referral_controller.ex
- lib/safira_web/router.ex
- lib/safira_web/views/referral_view.ex
- priv/repo/migrations/20180705013929_add_bages.exs
- priv/repo/migrations/20180705124446_create_referrals.exs
- test/safira/contest/contest_test.exs
- test/safira_web/controllers/referral_controller_test.exs
The badges resource needs too be accepted first for this pr to be accepted
> Referrals resource

- Book1.csv
- lib/mix/tasks/gen.badges.ex
- lib/safira/contest/contest.ex
- mix.exs
Format:
Coffee break;badge do lanche;2019-02-11;2019-02-12;/tmp/goraster.png
> Import badges csv

- lib/safira/accounts/auth.ex
- lib/safira_web/controllers/fallback_controller.ex
> Fix register message

- README.md
- lib/mix/tasks/gen.attendees.ex
- lib/mix/tasks/gen.badges.ex
- lib/safira/accounts/accounts.ex
- lib/safira/accounts/attendee.ex
- lib/safira/contest/contest.ex
- lib/safira_web/controllers/attendee_controller.ex
- lib/safira_web/controllers/leaderboard_controller.ex
- lib/safira_web/router.ex
- lib/safira_web/views/badge_view.ex
This fixes #43 
Adds the leaderboards by badge
Also fixes minor things like filter by only registered attendees and by volunteers
> Leaderboards

- lib/safira/accounts/accounts.ex
- lib/safira/accounts/auth.ex
This PR fixes bad request fixing #101
> Fix Sign Up bad input

- lib/mix/tasks/export.attendees.ex
Add task for exporting attendee information.
> Task for exporting Attendees information

- lib/mix/tasks/gen.company.ex
- lib/safira/accounts/company.ex
- lib/safira_web/controllers/company_controller.ex
- lib/safira_web/router.ex
- lib/safira_web/views/company_view.ex
- priv/repo/migrations/20210115125305_add_company_channel_id.exs
Add channel_id field to company schema.
Add update function in company_controller, so a manager can change some information about the company.
Change gent.company task, so it can take into account the new field.
Resolves: #144
> Company discord channel ID

- badges/desafios.csv
- badges/dias.csv
- badges/empresas.csv
- badges/outros.csv
- badges/talks.csv
- badges/verificacoes.csv
- badges/workshops.csv
Really simple PR which adds a "Token" collumn with the value of 1 to every badge csv.
All tests have been ran and redeems are working correctly.
> Add token collumn to badges CSVs

- lib/safira/interactions/bonus.ex
- lib/safira/interactions/interactions.ex
- priv/repo/migrations/20210215183051_create_bonuses.exs
Add Bonus Schema and Interaction Context.
Interaction context will contain both spotlight and bonus logics, once they encourage the interaction between attendees and companies.
> Add Bonus schema and Interaction context

- lib/safira/contest/contest.ex
- lib/safira_web/views/leaderboard_view.ex
Adds a tie breaker based on the token_balance of each attendee.
Resolves: #169
> Daily Leaderboard Break the Tie

- doc/endpoints.md
- lib/safira_web/controllers/bonus_controller.ex
- lib/safira_web/views/bonus_view.ex
Add a good return message when giving a bonus.
Add some documentation.
Resolves: #182
> Company Bonus - Return message with attendee name

- doc/endpoints.md
- lib/mix/tasks/gen.users_from_csv.ex
- lib/safira/accounts/attendee.ex
- lib/safira/store/redeemable.ex
Change some error messages as asked by the frontend team
Correct a mistake in the gen.users_from_csv task
> Update some error messages

- doc/endpoints.md
- lib/safira/contest/badge.ex
- lib/safira/roulette/roulette.ex
- lib/safira_web/controllers/roulette_controller.ex
- lib/safira_web/router.ex
- lib/safira_web/views/roulette_view.ex
Add latest 5 wins in Roulette, taking into account the `updated_at` field.
> Add latest 5 wins in Roulette

- lib/mix/tasks/gen.users_from_csv.ex
- lib/safira/email.ex
The gen.users_from_csv task now can read a csv file hosted either locally or remottely.
> Add remote call to gen_users task

- lib/mix/tasks/export.attendees.entries.ex
This PR adds:
- Task to export attendees and entries
> Export attendees and entries

- data/badges.csv
- lib/mix/tasks/gen.badges.ex
- lib/mix/tasks/gift.badge.ex
- lib/safira/contest/redeem.ex
- Changed begin and end field in badges.csv to datetime rather than date.
- Added verification before gifting a badge, which confirms whether current time is within the badge-gifting period for that activity
- Created function to check whether badge can be redeemed at that time
> Added date and time verification before giving badge

- lib/mix/tasks/gen.discord_users_from_csv.ex
- lib/mix/tasks/gen.users_from_csv.ex
- lib/safira/email.ex
Adds a new task `gen.discord_users_from_csv` that is a clone from the existing registration task, but the registration email sent will contain info to join our discord server
Closes #242
> Add task to send discord registration email

- lib/safira/contest/redeem.ex
> Admin Power Matters

- lib/safira/accounts/accounts.ex
- lib/safira/contest/contest.ex
- lib/safira_web/views/attendee_view.ex
- test/safira/accounts_test.exs
- test/safira_web/controllers/attendee_controller_test.exs
- test/safira_web/controllers/company_controller_test.exs
This was requested less than 24 hours before the event, very cool! I hope everything turns out good! Surely nothing will go wrong! 😀
> feat: add email to attendee view

- lib/safira/accounts/accounts.ex
Tested in staging, should work!
> fix: golds not seeing visitors

- lib/safira_web/live/landing/faqs_live/components/faq.ex
Closes #455 .
I just removed the animation if you want to merge this ASAP.
I can try and re-add it if you wish. However, I am struggling because any class placed in the first element of the tuples in the `in` and `out` parameters break the animation
> fix: faqs closing unexpectedly

- lib/safira_web/live/auth/user_login_live.ex
- lib/safira_web/live/auth/user_registration_live.html.heex
> feat: log in page

- config/config.exs
- lib/safira_web/controllers/error_html.ex
- lib/safira_web/controllers/error_html/404.html.heex
- lib/safira_web/controllers/error_html/500.html.heex
- test/safira_web/controllers/error_html_test.exs
> fix: error pages

- lib/safira/activities/speaker.ex
- lib/safira_web/live/backoffice/schedule_live/speaker_live/index.ex
> feat: add highlighted checkbox marker to speakers table

- lib/safira_web/components/layouts/app.html.heex
- lib/safira_web/components/layouts/backoffice.html.heex
- lib/safira_web/components/layouts/default.html.heex
- lib/safira_web/components/layouts/landing.html.heex
- lib/safira_web/components/layouts/root.html.heex
- lib/safira_web/live/landing/components/sparkles.ex
#447 introduced a bug on the application's layouts that caused Phoenix's Live Reload to just stop working.
[Apparently](https://elixirforum.com/t/livereload-iframe-code-not-injected-into-liveview/37254/2), the `root` layout **MUST** have the body tag on it (and not the child layouts), or else Phoenix fails to inject the hot reload `iframe`. 
_Oh well..._
> fix: hot reload

- lib/safira_web/live/backoffice/companies_live/form_component.ex
Make badge optional and improve logo upload.
> feat: improve companies form

- lib/safira_web/components/core_components.ex
- lib/safira_web/components/table.ex
- lib/safira_web/components/table_search.ex
- lib/safira_web/controllers/csv_controller.ex
- lib/safira_web/live/backoffice/attendee_live/index.html.heex
- lib/safira_web/router.ex
Adds export button and improves the table.
> feat: improve attendees page

- config/dev.exs
- lib/safira_web/live/landing/components/sparkles.ex
- priv/static/images/starts.svg
Convert the embedded SVG HTML to a separeted file in order to fix the Firefox blur bug
Bug:
> fix: firefox blur bug

- lib/safira_web/live/landing/components/speaker.ex
> fix: speaker with no activities crashing app

- lib/safira_web/controllers/user_session_controller.ex
- test/safira_web/controllers/user_session_controller_test.exs
Log in and log out flashes looked a bit odd, especially on mobile,
> feat: remove annoying flashes

- config/config.exs
- lib/safira_web/helpers.ex
> fix: credential page in deployment

- lib/safira_web/live/backoffice/companies_live/form_component.ex
- lib/safira_web/live/backoffice/spotlights_live/form_component.ex
- lib/safira_web/live/backoffice/spotlights_live/index.ex
- lib/safira_web/live/backoffice/spotlights_live/tiers/form_component.ex
Removes autofill for account data on company form; 
Makes it so that spotlight multipliers can be floats;
Changes some titles.
> feat: tweak inputs
