cesium/safira

lib/safira_web/controllers/attendee_controller.ex
lib/safira_web/controllers/redeem_controller.ex

Remove the specification of the company behaviour in the show
attendee, avoiding a GET from changing the attendee state.
Remove the plug Authorize in redeem_controller because there are 3
conditions in the create method where it is checked if the connection
belongs to a company or a manager, otherwise the connection is not
authorized and the redeem is not created. In this case the plug
is not needed.
Resolves: #93

Fix company redeem

---

lib/mix/tasks/gen.attendees.ex
lib/safira/accounts/accounts.ex
lib/safira/accounts/attendee.ex
lib/safira_web/controllers/auth_controller.ex
lib/safira_web/controllers/discord_association_controller.ex
lib/safira_web/router.ex
lib/safira_web/views/auth_view.ex
priv/repo/migrations/20210124200209_add_association_code_and_discord_id.exs
priv/repo/migrations/20210124200209_add_discord_association_code_and_discord_id.exs

- Add discord_association_code and discord_id fields to attendee
- Change gen.attendees task to also display the created discord_association_code
- Change signup to now return an association_code alongside the jwt, for the attendee to give as input to the discord bot
- Create DiscordAssociationController, used to associate an discord_id with an attendee given an discord_association_code 
- Create get_by_discord_id method for future use by other controllers which interact with the discord bot
Solves #137 
Some questions regarding code best practices will be left as comment

Implement discord association

---

lib/mix/tasks/gen.company.ex
lib/mix/tasks/gen.managers.ex
lib/mix/tasks/gen.user_with_badge.ex
lib/mix/tasks/gen.users_from_csv.ex
lib/safira/email.ex
lib/safira_web/controllers/password_controller.ex

- Create get.user_from_csv task, very simillar to gen.user_with_badges, but does not attribute the food/housing badges, reads the .csv locally instead of from a remote server, also renames references from enei to sei.
- Changes the manager's email domain from enei.pt to seium.org
- The mechanic associated with sending the emails is now inside of the Safira.Email module
- Change the CSV parser to RFC4180

Implement task to create users from csv (new)

---

lib/safira/contest/contest.ex
lib/safira_web/controllers/leaderboard_controller.ex
lib/safira_web/router.ex

Add new endpoint `get "/leaderboard/:date"`, where the :date represents the day we want to consult the leaderboard. This date is in the "YYYY-MM-DD" format, so a possible request to this endpoint could be `/api/v1/leaderboard/2021-02-05`.
Resolves: #139

Daily Leaderboard

---

config/config.exs
lib/safira_web/controllers/discord_association_controller.ex

`System.get_env` gets from the system environment, while `Application.fetch_env` gets from the applications environment.
The system-environment is not part of the application environment, since it is not any part of elixir or the BEAM. So, it should not be used in the application code. Only during the application initialization. Once the application is initialized, the environment should always be queried by `Application.fetch_env`.

Remove System.get_env from Controller

---

config/test.exs
lib/safira/accounts/attendee.ex
lib/safira/roulette.ex
lib/safira/roulette/attendee_prize.ex
lib/safira/roulette/prize.ex
priv/repo/migrations/20210209190634_create_prizes.exs
priv/repo/migrations/20210209232425_create_attendees_prizes.exs
test/factories/prize_factory.ex
test/safira/roulette_test.exs
test/strategies/prize_strategy.ex
test/support/data_case.ex
test/support/factory.ex

Add a new Context named Roulette, with 2 schemas. 
Prize represents a prize that an attendee can win by playing roulette.
AttendeePrice represents the intermediate table between the many to many Attendee-Prize association, and includes the quantity field which represents the number of times that an attendee won that Prize.
Some tests were automatically added, but I still changed a few things to make it work properly. (strategy and factory)

Roulette - Context and Schemas

---

lib/mix/tasks/gift.company.checkpoint.badge.ex

Add task that assigns badges to the attendees who have already visited a given number of companies, as well as the corresponding number of entries for the final draw.
Resolves: #172

Give checkpoint company badge Task

---

doc/endpoints.md
lib/mix/tasks/gift.company.checkpoint.badge.ex
lib/safira/contest/badge.ex

This PR adds:
- Turn gift checkpoint badges task to a generic task by passing the badge type as an argument;
- Remove badge type inconsistencies in `badge.ex`: #%{verificações: 0, secret: 1, desafios: 2, dias: 3, empresas: 4, oradores: 5, talks: 6, workshops: 7, outros: 8}
- Add some documentation;
Resolves: #178
Resolves: #188

Turn gift checkpoint badges task to a generic task

---

lib/safira/contest/contest.ex

Change sorter because of the Elixir version. `Enum.sort_by` changed the way of putting the sorter function, and Safira uses an older version.

Change sorter because of the Elixir version

---

lib/safira/roulette/roulette.ex

Roulette prizes have probabilities with more than 3 decimals. Just to be sure we needed to quadruply this precision.

Change round to 12 decimals

---

lib/safira/accounts/attendee.ex
lib/safira/contest/contest.ex
lib/safira/contest/daily_token.ex
lib/safira/interaction/interaction.ex
lib/safira/roulette/roulette.ex
lib/safira/store/store.ex
lib/safira_web/controllers/leaderboard_controller.ex
priv/repo/migrations/20211118225502_add_daily_token.exs

This PR fixes the daily leaderboard issue.
A new table was created (`daily_tokens`), where the last token balance of each day is stored for every user.
This table is updated everytime the user's token balance is changed.
Closes #229

Fix daily leaderboard

---

test/safira/roulette_test.exs

As you can see from here, `is_redeemable` is a required parameter:
```elixir
def changeset(prize, attrs) do
...
|> validate_required([:name, :stock, :max_amount_per_attendee, :probability, :is_redeemable])
...
end
```

Fix some roulette tests

---

lib/safira/web/uploaders/cv.ex
lib/safira_web/controllers/cv_controller.ex
lib/safira_web/router.ex
test/safira_web/controllers/cv_controller_test.exs

The generated zip file contains the CVs of the attendees of the company on the root.
Every CV is a `pdf` named after the attendee's nickname (which should be unique) (e.g. `zer0.pdf`)
This endpoint should only be accessible by the company itself or by an admin.

Add endpoint for a company to download the CVs of it's attendees

---

lib/mix/tasks/anonimize_users.ex
lib/mix/tasks/anonymize_users.ex

This can be useful if we want to do data mining in the future. This means we can offload this to someone that does not necessarily have access to prod without violating users' privacy

feat: add anonymize users task

---

lib/safira_web/cors.ex
lib/safira_web/router.ex

Removes version identifier from the API endpoints. Fixes #347

refactor: remove api versioning

---

data/wheel.csv
lib/safira/roulette/roulette.ex

Sometimes an attendee would roll the wheel and get a prize for which they had already received the maximum amount. This would cause an error, and the attendee would lose the tokens spent on the spin.
Now the wheel checks if the user has already received the maximum amount of the prize, and if so, spins again.

fix: check wheel prize validity

---

lib/safira/roulette/roulette.ex

A previous PR #350 , fixed an issue but introduced an error regarding the probabilities of the wheel prizes.
Now, if the wheel rolls a prize that the attendee already has the maximum amount of, it counts it as a loss and gives no prize.

fix: wheel probabilities

---

lib/safira/accounts/accounts.ex
lib/safira/admin/accounts.ex
lib/safira/roulette/roulette.ex
lib/safira_web/controllers/attendee_controller.ex
lib/safira_web/views/roulette_view.ex
test/safira/accounts_test.exs
test/safira_web/controllers/attendee_controller_test.exs
test/safira_web/controllers/roulette_controller_test.exs

This PR depends on https://github.com/cesium/seium.org/pull/604

feat: normalize profile mentions

---

lib/safira_web/controllers/spotlight/spotlight_controller.ex
lib/safira_web/router.ex
test/safira_web/controllers/spotlight_controller_test.exs

Since this endpoint will be used by the frontend server (and not an authenticated client), it needs to be public.

feat: make get current spotlight public

---

lib/safira_web/controllers/cv_controller.ex
test/safira_web/controllers/cv_controller_test.exs

The controller uses the function `Accounts.list_company_attendees/1` which already validates the sponsor tier of the company and returns the corresponding attendees that should be shown (Exclusive, Gold -> ALL CVs + STAFFS | Silver, Bronze -> ONLY VISITORS + STAFFS). The `has_cv` check was preventing Bronze and Silver sponsors from accessing the endpoint and consequently made them unable to download staff cvs.

fix: unecessary company CVs controller check

---

config/config.exs
config/runtime.exs
lib/safira/accounts/user_notifier.ex
lib/safira/mailer.ex
lib/safira_web/components/layouts/landing.html.heex
lib/safira_web/components/layouts/root.html.heex

fix: environment variables not loading on app config

---

lib/safira/uploader.ex

This was causing SVG files to be uploaded with `application/octet-stream` as the content type, making the images not appear on the HTML.

fix: s3 content types

---

lib/safira_web/live/backoffice/staff_live/index.ex
lib/safira_web/live/backoffice/staff_live/index.html.heex

Working with streams and `flop` at the same time is a pain in the ass. This removal helps ditching bugs related to runtime stream insertion and search functionalities.
Since pagination is already implemented (through `flop`), we wouldn't take that much advantage of streams, anyway.

fix: remove streams from staffs index

---

lib/safira_web/live/landing/components/schedule.ex

The issue is `Enum.group_by/3` does not preserve order. The solution was to create a custom group function ~~that gave me not-so-nice PF flashbacks~~

fix: activities not being correctly ordered

---

lib/safira/accounts/attendee.ex
lib/safira/accounts/roles/permissions.ex
lib/safira/activities.ex
lib/safira/activities/activity.ex
lib/safira/activities/enrolment.ex
lib/safira_web/components/forms.ex
lib/safira_web/controllers/user_session_controller.ex
lib/safira_web/live/auth/user_login_live.ex
lib/safira_web/live/auth/user_settings_live.ex
lib/safira_web/live/backoffice/schedule_live/activity_live/form_component.ex
lib/safira_web/live/backoffice/schedule_live/enrolment_live/form_component.ex
lib/safira_web/live/backoffice/schedule_live/index.ex
lib/safira_web/live/backoffice/schedule_live/index.html.heex
lib/safira_web/live/landing/components/schedule.ex
lib/safira_web/live/landing/home_live/index.ex
lib/safira_web/live/landing/home_live/index.html.heex
lib/safira_web/live/landing/schedule_live/index.ex
lib/safira_web/live/landing/schedule_live/index.html.heex
lib/safira_web/router.ex
priv/repo/migrations/20250117155628_add_enrolments.exs
test/safira/activities_test.exs

It stills needs some work, but I would like your opinion on the following:
I think the button should be visible even if the user is logged in. However, in that case, the user is redirected to the log in page. 
I believe it would be best if, after logging in, the user be automatically enrolled in the activity (assuming they already confirmed through the browser pop-up). However, I am struggling to see a solution that doesn't envolve a controller (as log in does not use LiveView). What do you think?

feat: activity enrollments

---

lib/safira_web/live/landing/components/footer.ex

#489 had a bug where the void section was over the links and preventing them to be clicked.

fix: footer links

---

lib/safira_web/components/avatar.ex

WebKit doesn't allow svgs inside the HTML to not have static dimensions attribute

fix: void avatar on safari

---

lib/safira_web/live/landing/components/navbar.ex
lib/safira_web/staff_roles.ex
lib/safira_web/user_auth.ex
priv/repo/seeds/slots.exs
priv/repo/seeds/teams.exs

This was causing problems in production because most staffs don't have access to the attendees page. 
Also, I think it will work better in the event.

chore: make scanner the default staff route

---

lib/safira_web/components/tabs.ex
lib/safira_web/live/backoffice/scanner_live/badge_live/index.ex
lib/safira_web/live/backoffice/scanner_live/index.ex
lib/safira_web/live/backoffice/scanner_live/index.html.heex
lib/safira_web/live/backoffice/scanner_live/inventory_live/index.ex
lib/safira_web/live/backoffice/scanner_live/inventory_live/show.ex
lib/safira_web/live/backoffice/store_live/product_live/index.html.heex
lib/safira_web/live/backoffice/store_live/purchase_live/form_component.ex
lib/safira_web/live/backoffice/store_live/purchase_live/index.ex
lib/safira_web/live/backoffice/store_live/purchase_live/index.html.heex
lib/safira_web/router.ex

feat: scanner redeems page

---

assets/js/hooks/qr_reading.js

If the permission to use the camera was denied in the scanner page then the user would not be able to go to any other page of the application (only after a f5 was it possible) because an error occurred due to a missing check in the scanner's logic.

fix: scanner breaking if permission to use the camera is denied/blocked
